#!/bin/sh
set -e
if [ -z "$SYSROOT" ]; then export SYSROOT="$(realpath "$(dirname "$0")/../sysroot")"; fi
if [ -z "$LLVMDIR" ]; then export LLVMDIR="$(realpath "$(dirname "$0")/../llvm-project")"; fi
if [ -f "$SYSROOT/bin/musl-gcc" ]; then export CC="$SYSROOT/bin/musl-gcc"; export SUPPORTS_LOCALIZATION="OFF"; fi
if [ -f "$SYSROOT/bin/musl-clang" ]; then export CC="$SYSROOT/bin/musl-clang"; export SUPPORTS_LOCALIZATION="ON"; fi

# libcxx needs futex.h in atomic.cpp for FUTEX_WAIT_PRIVATE and FUTEX_WAKE_PRIVATE
# the host linux header pulls in a ton of other headers, so let's just make one ourselves
mkdir -p "$SYSROOT/include/linux"
rm -f "$SYSROOT/include/linux/futex.h"
echo "#define FUTEX_WAIT_PRIVATE 128\n#define FUTEX_WAKE_PRIVATE 129" > "$SYSROOT/include/linux/futex.h"

rm -rf build1
mkdir build1
cd build1
export ASMFLAGS="-mcmodel=large -mstack-protector-guard=global -fno-use-cxa-atexit -fno-pic -fno-pie -fcf-protection=none"
export CFLAGS="-mcmodel=large -mstack-protector-guard=global -fno-use-cxa-atexit -fno-pic -fno-pie -fcf-protection=none"
export CXXFLAGS="-mcmodel=large -mstack-protector-guard=global -fno-use-cxa-atexit -fno-pic -fno-pie -fcf-protection=none"
export LDFLAGS="-Wl,--no-pie"

# LIBCXX_ENABLE_LOCALIZATION is set to OFF in musl-gcc due to an llvm bug (see https://bugs.gentoo.org/869038), re-enable on next stable release
# note some cores cannot be built this way (melonDS, snes9x, uzem, MAME), those will need to use musl-clang in the meantime

cmake \
	-DCMAKE_ASM_COMPILER="$CC" \
	-DCMAKE_C_COMPILER="$CC" \
	-DCMAKE_CXX_COMPILER="$CC" \
	-DLIBCXX_ENABLE_SHARED=OFF \
	-DLIBCXX_CXX_ABI="system-libcxxabi" \
	-DLIBCXX_CXX_ABI_INCLUDE_PATHS="$LLVMDIR/libcxxabi/include" \
	-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
	-DLIBCXX_ENABLE_RANDOM_DEVICE=OFF \
	-DLIBCXX_ENABLE_LOCALIZATION="$SUPPORTS_LOCALIZATION" \
	-DLIBCXX_HAS_MUSL_LIBC=ON \
	-DLIBCXX_USE_COMPILER_RT=ON \
	-DLIBCXX_INCLUDE_TESTS=OFF \
	-DLIBCXX_INCLUDE_BENCHMARKS=OFF \
	-DLIBCXX_INCLUDE_DOCS=OFF \
	-DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=OFF \
	-DCMAKE_INSTALL_PREFIX="$SYSROOT" \
	-DCMAKE_AR="$(which llvm-ar)" \
	-DCMAKE_RANLIB="$(which llvm-ranlib)" \
	-DPython3_EXECUTABLE="$(which python3)" \
	$LLVMDIR/libcxx
