#!/bin/sh
set -e
if [ -z "$SYSROOT" ]; then export SYSROOT="$(realpath "$(dirname "$0")/../sysroot")"; fi
if [ -z "$LLVMDIR" ]; then export LLVMDIR="$(realpath "$(dirname "$0")/../llvm-project")"; fi

rm -rf build1
mkdir build1
cd build1
export CFLAGS="-mcmodel=large -mstack-protector-guard=global -fno-use-cxa-atexit -no-pie -fno-pic -fno-pie"
export CXXFLAGS="-mcmodel=large -mstack-protector-guard=global -fno-use-cxa-atexit -no-pie -fno-pic -fno-pie"
cmake \
	-DCMAKE_C_COMPILER="$SYSROOT/bin/musl-gcc" \
	-DCMAKE_CXX_COMPILER="$SYSROOT/bin/musl-gcc" \
	-DLIBCXXABI_ENABLE_EXCEPTIONS=ON \
	-DLIBCXXABI_ENABLE_PIC=OFF \
	-DLIBCXXABI_ENABLE_SHARED=OFF \
	-DLIBCXXABI_BAREMETAL=ON \
	-DLIBCXXABI_SILENT_TERMINATE=ON \
	-DLIBCXXABI_USE_LLVM_UNWINDER=ON \
	-DLIBCXXABI_USE_COMPILER_RT=ON \
	-DLIBCXXABI_INCLUDE_TESTS=OFF \
	-DLIBCXXABI_LINK_TESTS_WITH_SHARED_LIBCXXABI=OFF \
	-DLIBCXXABI_LIBCXX_INCLUDES="$LLVMDIR/libcxx/include" \
	-DCMAKE_INSTALL_PREFIX="$SYSROOT" \
	-DCMAKE_AR="/usr/bin/gcc-ar" \
	-DCMAKE_RANLIB="/usr/bin/gcc-ranlib" \
	$LLVMDIR/libcxxabi
