#include "_PDCLIB_glue.h"
#include <threads.h>


#undef WIN32
#undef _WIN32
#define DLMALLOC_EXPORT  _PDCLIB_API
#define MALLOC_ALIGNMENT _PDCLIB_MALLOC_ALIGN
#define MSPACES 0
#define USE_LOCKS 0
#define USE_SPIN_LOCKS 0
#define USE_RECURSIVE_LOCKS 0
#undef NEED_GLOBAL_LOCK_INIT
#define FOOTERS 0
#undef USE_DL_PREFIX
#define MALLOC_INSPECT_ALL 0
#define ABORT abort()
#define PROCEED_ON_ERROR 0
#define DEBUG 0
#define ABORT_ON_ASSERT_FAILURE 1
#define MALLOC_FAILURE_ACTION errno = ENOMEM
#define HAVE_MORECORE 1
#define MORECORE _PDCLIB_sbrk
#define MORECORE_CONTIGUOUS 1
#define MORECORE_CANNOT_TRIM 1
#define NO_SEGMENT_TRAVERSAL 0
#define HAVE_MMAP 0
#define HAVE_MREMAP 0
#define USE_BUILTIN_FFS 0
#define malloc_getpagesize _PDCLIB_MALLOC_PAGESIZE
#define USE_DEV_RANDOM 0
#define NO_MALLINFO 1
#define MALLINFO_FIELD_TYPE size_t
#define NO_MALLOC_STATS 1
#define DEFAULT_GRANULARITY _PDCLIB_MALLOC_GRANULARITY
#define DEFAULT_TRIM_THRESHOLD _PDCLIB_MALLOC_TRIM_THRESHOLD
#define DEFAULT_MMAP_THREHOLD _PDCLIB_MALLOC_MMAP_THRESHOLD
#define MAX_RELEASE_CHECK_RATE _PDCLIB_MALLOC_RELEASE_CHECK_RATE

/* C standard says this is so */
#define REALLOC_ZERO_BYTES_FREES 1
#define LACKS_UNISTD_H
#define LACKS_FCNTL_H
#define LACKS_SYS_PARAM_H
#define LACKS_SYS_MMAN_H
#define LACKS_STRINGS_H
#define LACKS_SYS_TYPES_H
#define LACKS_SCHED_H
#include <stdlib.h>
#include <errno.h>
