// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

public enum InputType : byte
{
  Padding = 0,
  Button = 1,
  ButtonCanRapid = 2,
  Switch = 3,
  Status = 4,
  Axis = 5,
  PointerX = 6,
  PointerY = 7,
  AxisRel = 8,
  ByteSpecial = 9,
  ResetButton = 10,
  ButtonAnalog = 11,
  Rumble = 12,
};


}
