const char rom_db_data[] = "T-081326 {\n"
"	name NBA Jam\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 256\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				1 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-81033 {\n"
"	name NBA Jam\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 256\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				1 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-081276 {\n"
"	name NFL Quarterback Club\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 256\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			#This is almost certainly not correct based on the address pins\n"
"			#available to the Acclaim mapper. It's probably available up to\n"
"			#2FFFFF at least and just fights with D0 from the mask ROM\n"
"			last 200001\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				8 scl\n"
"			}\n"
"		}\n"
"		200002 {\n"
"			device ROM\n"
"			offset 200000\n"
"			last 2FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-81406 {\n"
"	name NBA Jam TE\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 512\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			#This is almost certainly not correct based on the address pins\n"
"			#available to the Acclaim mapper. It's probably available up to\n"
"			#2FFFFF at least and just fights with D0 from the mask ROM\n"
"			last 200001\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				8 scl\n"
"			}\n"
"		}\n"
"		200002 {\n"
"			device ROM\n"
"			offset 200000\n"
"			last 2FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-081586 {\n"
"	name NFL Quarterback Club '96\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 2048\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			#This is almost certainly not correct based on the address pins\n"
"			#available to the Acclaim mapper. It's probably available up to\n"
"			#2FFFFF at least and just fights with D0 from the mask ROM\n"
"			last 200001\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				8 scl\n"
"			}\n"
"		}\n"
"		200002 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"			offset 200000\n"
"		}\n"
"	}\n"
"}\n"
"T-81576 {\n"
"	name College Slam\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 8192\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			#This is almost certainly not correct based on the address pins\n"
"			#available to the Acclaim mapper. It's probably available up to\n"
"			#2FFFFF at least and just fights with D0 from the mask ROM\n"
"			last 200001\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				8 scl\n"
"			}\n"
"		}\n"
"		200002 {\n"
"			device ROM\n"
"			offset 200000\n"
"			last 2FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-81476 {\n"
"	name Frank Thomas Big Hurt Baseball\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 8192\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			#This is almost certainly not correct based on the address pins\n"
"			#available to the Acclaim mapper. It's probably available up to\n"
"			#2FFFFF at least and just fights with D0 from the mask ROM\n"
"			last 200001\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				8 scl\n"
"			}\n"
"		}\n"
"		200002 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"			offset 200000\n"
"		}\n"
"	}\n"
"}\n"
"T-50176 {\n"
"	name Rings of Power\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"			bits_write {\n"
"				6 scl\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-50396 {\n"
"	name NHLPA Hockey '93\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 7FFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"			bits_write {\n"
"				6 scl\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-50446 {\n"
"	name John Madden Football '93\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"			bits_write {\n"
"				6 scl\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-50516 {\n"
"	name John Madden Football '93: Championship Edition\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"			bits_write {\n"
"				6 scl\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-172196 {\n"
"	name Madden NFL 98\n"
"	SRAM {\n"
"		size 16318\n"
"		bus odd\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device SRAM\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-50606 {\n"
"	name Bill Walsh College Football\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"			bits_write {\n"
"				6 scl\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"MK-1228 {\n"
"	name Greatest Heavyweights of the Ring\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"G-5538 {\n"
"	name Greatest Heavyweights of the Ring\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"PR-1993 {\n"
"	name Greatest Heavyweights of the Ring (Prototype)\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"00001211 {\n"
"	name Sports Talk Baseball\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"00004076 {\n"
"	name Honoo no Toukyuuji Dodge Danpei\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"00054503 {\n"
"	name Game Toshokan\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-120106 {\n"
"	name Brian Lara Cricket\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 1024\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-120146 {\n"
"	name Brian Lara Cricket 96\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 8192\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"e8ff759679a0df2b3f9ece37ef686f248d3cf37b {\n"
"	name Micro Machines: Turbo Tournament '96\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 2048\n"
"	}\n"
"	#TODO: J-Cart\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 387FFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"		388000 {\n"
"			device jcart\n"
"			last 38FFFF\n"
"		}\n"
"	}\n"
"}\n"
"9f47fcc7bb2f5921cb1c3beb06b668ffb292cb08 {\n"
"	name Micro Machines: Turbo Tournament '96\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 2048\n"
"	}\n"
"	#TODO: J-Cart\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"6d3df64ab8bb0b559f216adca62d1cdd74704a26 {\n"
"	name Micro Machines: Military\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 1024\n"
"	}\n"
"	#TODO: J-Cart\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 387FFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"		388000 {\n"
"			device jcart\n"
"			last 38FFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-120096 {\n"
"	name Micro Machines 2: Turbo Tournament\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 2048\n"
"	}\n"
"	#TODO: J-Cart\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 2FFFFF\n"
"		}\n"
"		300000 {\n"
"			device EEPROM\n"
"			last 37FFFF\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"		380000 {\n"
"			device EEPROM\n"
"			last 387FFF\n"
"			bits_read {\n"
"				7 sda\n"
"			}\n"
"		}\n"
"		388000 {\n"
"			device jcart\n"
"			last 38FFFF\n"
"		}\n"
"	}\n"
"}\n"
"MK-12056 {\n"
"	name Super Street Fighter 2: The New Challengers\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 7FFFF\n"
"		}\n"
"		80000 {\n"
"			device Sega mapper\n"
"			last 3FFFFF\n"
"			offset 80000\n"
"		}\n"
"	}\n"
"}\n"
"T-12056 {\n"
"	name Super Street Fighter 2: The New Challengers\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 7FFFF\n"
"		}\n"
"		80000 {\n"
"			device Sega mapper\n"
"			last 3FFFFF\n"
"			offset 80000\n"
"		}\n"
"	}\n"
"}\n"
"T-12043 {\n"
"	name Super Street Fighter 2: The New Challengers\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 7FFFF\n"
"		}\n"
"		80000 {\n"
"			device Sega mapper\n"
"			last 3FFFFF\n"
"			offset 80000\n"
"		}\n"
"	}\n"
"}\n"
"T-12046 {\n"
"	name Mega Man - The Wily Wars\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-12053 {\n"
"	name Rockman Mega World\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"MK-1079 {\n"
"	#This entry is needed only to make this play nicely with\n"
"	#S&K lock-on support. Normal 2MB cartridges with SRAM won't\n"
"	#work right, but Sonic 3 has the limited SRAM-only variant\n"
"	#of Sega's mapper commonly found on 4MB carts with SRAM\n"
"	name Sonic the Hedgehog 3\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device Sega mapper\n"
"			variant save-only\n"
"			offset 200000\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"	\n"
"}\n"
"MK-1563 {\n"
"	name Sonic & Knuckles\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device LOCK-ON\n"
"			last 3FFFFF\n"
"			offset 200000\n"
"		}\n"
"	}\n"
"}\n"
"G-4060 {\n"
"	name Wonder Boy in Monster World\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"G-4524 {\n"
"	name Ninja Burai Densetsu\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"T-70106- {\n"
"	name Another World\n"
"	#European version of this game has EUROPE in the region field rather than just E\n"
"	regions E\n"
"}\n"
"G-004130 {\n"
"	name Alien Soldier\n"
"	#Japanese version of this game seems to indicate support for European consoles in\n"
"	#the header. While the game does indeed run, most people probably expect 60Hz\n"
"	#if they are running the Japanese version rather than the European one\n"
"	regions J\n"
"}\n"
"G-005545 {\n"
"	name Light Crusader\n"
"	#Japanese version of this game seems to indicate support for European consoles in\n"
"	#the header. While the game does indeed run, most people probably expect 60Hz\n"
"	#if they are running the Japanese version rather than the European one\n"
"	regions J\n"
"}\n"
"\n"
"00004042 {\n"
"	name Castle of Illusion: Fushigi no Oshiro Daibouken\n"
"	#Has JAPAN in header rather than J, A gets interpreted as a \"new-style\" code\n"
"	regions J\n"
"}\n"
"T-48036 {\n"
"	name Ms. Pac-Man\n"
"	#Ms. Pac-Man doesn't like 6-button controllers\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n"
"T-103026 {\n"
"	name King of the Monsters\n"
"	#This game won't work at all with a properly emualted 6-button controller\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n"
"T-119106 {\n"
"	name Combat Cars\n"
"	#Routine in the main game seems to work fine with 6-button controllers,\n"
"	#but options menu has problems.\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n"
"T-113106 {\n"
"	name Second Samurai\n"
"	#Pause doesn't work right with a 6-button controller\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n"
"MK-1304 {\n"
"	name Dungeons & Dragons - Warriors of the Eternal Sun\n"
"	#Switching characters cycles too fast with a 6-button controller\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n"
"#Automatically hook up the mouse in the appropriate port for the games I've tested\n"
"T-76076 {\n"
"	name Nobunaga's Ambition\n"
"	device_overrides {\n"
"		2 mouse.1\n"
"	}\n"
"}\n"
"T-97056 {\n"
"	name Fun 'N' Games\n"
"	device_overrides {\n"
"		2 mouse.1\n"
"	}\n"
"}\n"
"MK-1552 {\n"
"	name Richard Scarry's Busytown\n"
"	device_overrides {\n"
"		1 mouse.1\n"
"	}\n"
"}\n"
"MK-1713 {\n"
"	name Wacky Worlds\n"
"	device_overrides {\n"
"		2 mouse.1\n"
"	}\n"
"}\n"
"T-97056- {\n"
"	name Fun 'n' Games\n"
"	device_overrides {\n"
"		2 mouse.1\n"
"	}\n"
"}\n"
"T-130016 {\n"
"	name Shanghai II: Dragon's Eye\n"
"	device_overrides {\n"
"		1 mouse.1\n"
"	}\n"
"}\n"
"T-50286 {\n"
"	name Buck Rogers: Countdown to Doomsday\n"
"	SRAM {\n"
"		size 8192\n"
"		bus odd\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device SRAM\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"MK-1215 {\n"
"	name Evander 'Real Deal' Holyfield's Boxing\n"
"	EEPROM {\n"
"		type i2c\n"
"		size 128\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device EEPROM\n"
"			last 3FFFFF\n"
"			bits_read {\n"
"				0 sda\n"
"			}\n"
"			bits_write {\n"
"				0 sda\n"
"				1 scl\n"
"			}\n"
"		}\n"
"	}\n"
"}\n"
"ACLD012 {\n"
"	name Hardball III\n"
"	SRAM {\n"
"		size 32768\n"
"		bus odd\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device SRAM\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"T-50166 {\n"
"	name Might and Magic - Gates to Another World\n"
"	SRAM {\n"
"		size 32768\n"
"		bus odd\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device SRAM\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"9bed099693c27a6575b394bdd150efb7cc53c5c6 {\n"
"	name Atomic Robo-Kid\n"
"	regions J\n"
"}\n"
"d366d05644eb59a14baf3c2e7281c1584630c021 {\n"
"	name Might and Magic III - Isles of Terra\n"
"	SRAM {\n"
"		size 32768\n"
"		bus odd\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device SRAM\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"8fe0806427e123717ba20478ab1410c25fa942e6 {\n"
"	name Ya Se Chuan Shuo\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 6300\n"
"			last 400001\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value 9800\n"
"			last 400003\n"
"		}\n"
"		400004 {\n"
"			device fixed\n"
"			value C900\n"
"			last 400005\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value 1800\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"7857c797245b52641a3d1d4512089bccb0ed5359 {\n"
"	name 16 Zhang Ma Jiang\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value AA00\n"
"			last 400003\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value F000\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"5fc4591fbb1acc64e184466c7b6287c7f64e0b7a {\n"
"	name Elf Wor\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 5500\n"
"			last 400001\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value 0F00\n"
"			last 400003\n"
"		}\n"
"		400004 {\n"
"			device fixed\n"
"			value C900\n"
"			last 400005\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value 1800\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"df7a2527875317406b466175f0614d343dd32117 {\n"
"	name Huan Le Tao Qi Shu: Smart Mouse\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 5500\n"
"			last 400001\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value 0F00\n"
"			last 400003\n"
"		}\n"
"		400004 {\n"
"			device fixed\n"
"			value AA00\n"
"			last 400005\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value F000\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"25d2d6a5ab20e16b8b42b67e5fb338421b64b29b {\n"
"	name Mighty Morphin' Power Rangers: The Fighting Edition\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 5500\n"
"			last 400001\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value 0F00\n"
"			last 400003\n"
"		}\n"
"		400004 {\n"
"			device fixed\n"
"			value C900\n"
"			last 400005\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value 1800\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"03f40c14624f1522d6e3105997d14e8eaba12257 {\n"
"	name Super Bubble Bobble MD\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 5500\n"
"			last 400001\n"
"		}\n"
"		400002 {\n"
"			device fixed\n"
"			value 0F00\n"
"			last 400003\n"
"		}\n"
"	}\n"
"}\n"
"3dca68795b6c9a16cafa5e71218d5ce83aa465fc {\n"
"	name Thunderbolt II\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device fixed\n"
"			value 5500\n"
"			last 400001\n"
"		}\n"
"		400006 {\n"
"			device fixed\n"
"			value F000\n"
"			last 400007\n"
"		}\n"
"	}\n"
"}\n"
"2a561b6e47c93272fe5947084837d9f6f514ed38 {\n"
"	name Squirrel King\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device RAM\n"
"			size 2\n"
"			bus both\n"
"			last 7FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"\n"
"#This entry is used by the GUI ROM\n"
"BlstMenu {\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last FFFFF\n"
"		}\n"
"		100000 {\n"
"			device RAM\n"
"			size 80000\n"
"			last 17FFFF\n"
"		}\n"
"		180000 {\n"
"			device MENU\n"
"			last 1FFFFF\n"
"		}\n"
"	}\n"
"	device_overrides {\n"
"		1 gamepad3.1\n"
"		2 mouse.1\n"
"		ext none\n"
"	}\n"
"	mouse_mode absolute\n"
"}\n"
"\n"
"6568b3a4e096159776ef8687a80d43589741fd60 {\n"
"	name Magistr 16 BIOS\n"
"	NOR {\n"
"		size 262144\n"
"		page_size 128\n"
"		product_id DA45\n"
"		bus even\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		400000 {\n"
"			device NOR\n"
"			last 5FFFFF\n"
"		}\n"
"#		600000 {\n"
"#			device Super IO\n"
"#			last 7FFFFF\n"
"#		}\n"
"		E00000 {\n"
"			device RAM\n"
"			size 40000\n"
"			last FFFFFF\n"
"			bus both\n"
"		}\n"
"	}\n"
"}\n"
"\n"
"7313c20071de0ab1cd84ac1352cb0ed1c4a4afa8 {\n"
"	#This appears to be an underdump, but it seems to be the only copy floating around \n"
"	name 12-in-1\n"
"	map {\n"
"		0 {\n"
"			device multi-game\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"6b2a6de2622735f6d56c6c9c01f74daa90e355cb {\n"
"	name Super 15-in-1\n"
"	map {\n"
"		0 {\n"
"			device multi-game\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"e1c041ba69da087c428dcda16850159f3caebd4b {\n"
"	name Super 19-in-1\n"
"	map {\n"
"		0 {\n"
"			device multi-game\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"31c66bd13abf4ae8271c09ec5286a0ee0289dbbc {\n"
"	#Designed to run on Sega Channel hardware which is RAM-based\n"
"	#writes to the this RAM qutie a bit to select games\n"
"	name Game no Kanzume Otokuyou\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"			writeable yes\n"
"		}\n"
"	}\n"
"}\n"
"cda73e4caf53cbc8f0750b69e5e7f394ad3735d1 {\n"
"	name MegaWiFi Bootloader\n"
"	NOR {\n"
"		size 4194304\n"
"		page_size 128\n"
"		product_id DA45\n"
"		bus both\n"
"		init ROM\n"
"		cmd_address1 AAB\n"
"		cmd_address2 555\n"
"	}\n"
"	map {\n"
"		0 {\n"
"			device NOR\n"
"			last 3FFFFF\n"
"		}\n"
"		A130C0 {\n"
"			device megawifi\n"
"			last A130CF\n"
"		}\n"
"	}\n"
"}\n"
"222a66cdb8865a7f89e5a72418413888bb400176 {\n"
"	#I've personally confirmed this version had a J-Cart\n"
"	#release, but unlike the other revision it runs without it\n"
"	name Pete Sampras Tennis\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device jcart\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"4c830ace4590294bb374b4cab71ebebf44d9a07a {\n"
"	#This version will not accept input if J-Cart hardware is missing\n"
"	name Pete Sampras Tennis\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 1FFFFF\n"
"		}\n"
"		200000 {\n"
"			device jcart\n"
"			last 3FFFFF\n"
"		}\n"
"	}\n"
"}\n"
"NETO-001 {\n"
"	name Sonic Delta\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 7FFFF\n"
"		}\n"
"		80000 {\n"
"			device Sega mapper\n"
"			last 3FFFFF\n"
"			offset 80000\n"
"		}\n"
"	}\n"
"}\n"
"5e5ca20b39122c86b8f662bd8014af674f9dbed7 {\n"
"	name Rock Heaven\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		500008 {\n"
"			device fixed\n"
"			value 5082\n"
"			last 500009\n"
"		}\n"
"	}\n"
"}\n"
"68366449fd1497538741b5a1949e342202d48948 {\n"
"	name Rock World\n"
"	map {\n"
"		0 {\n"
"			device ROM\n"
"			last 3FFFFF\n"
"		}\n"
"		500008 {\n"
"			device fixed\n"
"			value 4000\n"
"			last 500009\n"
"		}\n"
"		500208 {\n"
"			device fixed\n"
"			value A000\n"
"			last 500209\n"
"		}\n"
"		\n"
"	}\n"
"}\n"
"T-122026 {\n"
"	name Outback Joey\n"
"	HeartbeatTrainer {\n"
"		size 512\n"
"	}\n"
"	device_overrides {\n"
"		1 heartbeat_trainer.1\n"
"		2 gamepad3.2\n"
"	}\n"
"}\n";
