CXXFLAGS := \
	-Wall -Werror=int-to-pointer-cast \
	-Wno-reorder \
	-std=c++0x -fomit-frame-pointer \
	-DNOGDB

TARGET := uzem.wbx

SRCS = $(shell find $(ROOT_DIR) -type f -name '*.cpp')

include ../common.mak
