flags += -DGB_INTERNAL -DGB_DISABLE_DEBUGGER -DGB_DISABLE_CHEATS -D_GNU_SOURCE -Wno-multichar
options += -I../sameboy

objects += gb-apu gb-camera gb-rumble gb-display gb-gb gb-joypad gb-mbc
objects += gb-memory gb-printer gb-random gb-rewind gb-save_state gb-sgb
objects += gb-sm83_cpu gb-symbol_hash gb-timing
#objects+= gb-debugger gb-sm83_disassembler

obj/gb-apu.o:               gb/Core/apu.c
obj/gb-camera.o:            gb/Core/camera.c
obj/gb-debugger.o:          gb/Core/debugger.c
obj/gb-rumble.o:            gb/Core/rumble.c
obj/gb-display.o:           gb/Core/display.c
obj/gb-gb.o:                gb/Core/gb.c
obj/gb-joypad.o:            gb/Core/joypad.c
obj/gb-mbc.o:               gb/Core/mbc.c
obj/gb-memory.o:            gb/Core/memory.c
obj/gb-printer.o:           gb/Core/printer.c
obj/gb-random.o:            gb/Core/random.c
obj/gb-rewind.o:            gb/Core/rewind.c
obj/gb-save_state.o:        gb/Core/save_state.c
obj/gb-sgb.o:               gb/Core/sgb.c
obj/gb-sm83_cpu.o:          gb/Core/sm83_cpu.c
obj/gb-sm83_disassembler.o: gb/Core/sm83_disassembler.c
obj/gb-symbol_hash.o:       gb/Core/symbol_hash.c
obj/gb-timing.o:            gb/Core/timing.c
