CXXFLAGS := \
	-Wall -Werror=int-to-pointer-cast \
	-std=c++0x -fomit-frame-pointer -fno-exceptions -fno-rtti

TARGET = dobie.wbx

SRCS = $(shell find $(ROOT_DIR)/dobiestation/src/core -type f -name '*.cpp')

include ../common.mak
