console.clear()
console.writeline("--cleared previous output")
console.log("--Logging", "multiple", "values", "in one", "call")
console.write("--console.write does not include a new line")
console.writeline("--but console.writeline does")
console.writeline("--next line", "--next line")
print("--Print Single value")
console.writeline("--Log a lua table:")
console.log(joypad.get())
