// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

[System.FlagsAttribute]
public enum DeviceFlags : byte
{
  Keyboard = 1,
  Unique = 2,
};


}
