// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

public enum InputType : byte
{
  Padding0 = 0,
  Padding1 = 1,
  Button = 2,
  ButtonCanRapid = 3,
  Switch = 4,
  Status = 5,
  Axis = 6,
  PointerX = 7,
  PointerY = 8,
  AxisRel = 9,
  ByteSpecial = 10,
  ResetButton = 11,
  ButtonAnalog = 12,
  Rumble = 13,
};


}
