// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct NButtonInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static NButtonInfo GetRootAsNButtonInfo(ByteBuffer _bb) { return GetRootAsNButtonInfo(_bb, new NButtonInfo()); }
  public static NButtonInfo GetRootAsNButtonInfo(ByteBuffer _bb, NButtonInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NButtonInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ExcludeName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetExcludeNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetExcludeNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetExcludeNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<NymaTypes.NButtonInfo> CreateNButtonInfo(FlatBufferBuilder builder,
      StringOffset ExcludeNameOffset = default(StringOffset)) {
    builder.StartTable(1);
    NButtonInfo.AddExcludeName(builder, ExcludeNameOffset);
    return NButtonInfo.EndNButtonInfo(builder);
  }

  public static void StartNButtonInfo(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddExcludeName(FlatBufferBuilder builder, StringOffset excludeNameOffset) { builder.AddOffset(0, excludeNameOffset.Value, 0); }
  public static Offset<NymaTypes.NButtonInfo> EndNButtonInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<NymaTypes.NButtonInfo>(o);
  }
  public NButtonInfoT UnPack() {
    var _o = new NButtonInfoT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(NButtonInfoT _o) {
    _o.ExcludeName = this.ExcludeName;
  }
  public static Offset<NymaTypes.NButtonInfo> Pack(FlatBufferBuilder builder, NButtonInfoT _o) {
    if (_o == null) return default(Offset<NymaTypes.NButtonInfo>);
    var _ExcludeName = _o.ExcludeName == null ? default(StringOffset) : builder.CreateString(_o.ExcludeName);
    return CreateNButtonInfo(
      builder,
      _ExcludeName);
  }
}

public class NButtonInfoT
{
  public string ExcludeName { get; set; }

  public NButtonInfoT() {
    this.ExcludeName = null;
  }
}


static public class NButtonInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*ExcludeName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
