// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

[System.FlagsAttribute]
public enum PortFlags : byte
{
  NoUserSelect = 1,
};


}
