// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

public enum SettingType : int
{
  /// (signed), int8, int16, int32, int64(saved as)
  Int = 0,
  /// uint8, uint16, uint32, uint64(saved as)
  Uint = 1,
  /// 0 or 1
  Bool = 2,
  /// float64
  Float = 3,
  String = 4,
  /// string value from a list of potential strings
  Enum = 5,
  /// TODO: How do these work
  MultiEnum = 6,
  /// Shouldn't see any of these
  Alias = 7,
};


}
