// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace NymaTypes
{

[System.FlagsAttribute]
public enum SettingsFlags : uint
{
  /// TODO(cats)
  Input = 1,
  Sound = 2,
  Video = 4,
  /// User-configurable physical->virtual button/axes and hotkey mappings(driver-side code category mainly).
  InputMapping = 8,
  Path = 16,
  /// If the setting affects emulation from the point of view of the emulated program
  EmuState = 256,
  /// If it's safe for an untrusted source to modify it, probably only used in conjunction with MDFNST_EX_EMU_STATE and network play
  UntrustedSafe = 512,
  /// Suppress documentation generation for this setting.
  SuppressDoc = 1024,
  /// Auto-generated common template setting(like nes.xscale, pce.xscale, vb.xscale, nes.enable, pce.enable, vb.enable)
  CommonTemplate = 2048,
  /// Don't save setting in settings file.
  NonPersistent = 4096,
  /// TODO(in progress)
  RequiresReload = 16384,
  RequiresRestart = 32768,
};


}
