cd bin/Release/BizHawk.app/Contents/MonoBundle/
rm dll/libgambatte.dll 
rm dll/libco_msvc_win32.dll 
rm dll/libspeexdsp.dll 
rm dll/ffmpeg.exe 
rm dll/ffmpeg_readme.txt 
rm zip.exe
rm dll/libmeteor.dll
rm dll/MusashiDLL.dll
rm dll/libmednahawk.dll
rm dll/libsneshawk-32-compatibility.dll
rm dll/libsneshawk-64-compatibility.dll
rm dll/libsneshawk-32-performance.dll
rm dll/libsneshawk-64-performance.dll
rm dll/blip_buf.dll
rm dll/PPSSPPBizhawk.dll
rm dll/libyabause.dll
rm dll/mupen64plus-audio-bkm.dll
rm dll/mupen64plus-input-bkm.dll
rm dll/mupen64plus-rsp-hle.dll
rm dll/mupen64plus-video-glide64.dll
rm dll/mupen64plus-video-glide64mk2.dll
rm dll/mupen64plus-video-rice.dll
rm dll/mupen64plus.dll
rm dll/SDL.dll
rm dll/at3plusdecoder.dll
rm dll/freetype6.dll
rm dll/libgenplusgx.dll
rm dll/libquicknes.dll
mv dll/LuaInterface.dll .
rm dll/mupen64plus-rsp-z64-hlevideo.dll
rm dll/libsneshawk-32-accuracy.exe
rm dll/mupen64plus-video-jabo.dll
rm dll/libvbanext.dll
rm dll/bizswan.dll
rm dll/d3d8.dll
rm liblua5.1.dylib
rm dll/Jabo_Direct3D8_patched.dll
rm dll/bizlynx.dll
rm dll/libbizsnes.dll
rm dll/libpng12.dll
rm dll/lua51.dll
rm dll/octoshock.dll
rm dll/openal32.dll
rm dll/mgba.dll
rm dll/Virtu.dll
rm gpgx.elf
rm dll/cgc.exe
rm dll/libdarm.dll
chmod +x dll/cgc_osx
chmod +x dll/ffmpeg_osx
