SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_C_COMPILER   powerpc-eabi-gcc)
SET(CMAKE_CXX_COMPILER powerpc-eabi-g++)

SET(CMAKE_FIND_ROOT_PATH /opt/devkitpro/devkitPPC/powerpc-eabi/)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(WII 1)
