processors += wdc65816 spc700 arm7tdmi

objects += sfc-interface sfc-system sfc-controller
objects += sfc-cartridge sfc-memory
objects += sfc-cpu sfc-smp sfc-dsp sfc-ppu sfc-ppu-fast
objects += sfc-expansion sfc-coprocessor sfc-slot

obj/sfc-interface.o:   sfc/interface/interface.cpp
obj/sfc-system.o:      sfc/system/system.cpp
obj/sfc-controller.o:  sfc/controller/controller.cpp
obj/sfc-cartridge.o:   sfc/cartridge/cartridge.cpp
obj/sfc-memory.o:      sfc/memory/memory.cpp

obj/sfc-cpu.o:         sfc/cpu/cpu.cpp
obj/sfc-smp.o:         sfc/smp/smp.cpp
obj/sfc-dsp.o:         sfc/dsp/dsp.cpp
obj/sfc-ppu.o:         sfc/ppu/ppu.cpp
obj/sfc-ppu-fast.o:    sfc/ppu-fast/ppu.cpp

obj/sfc-expansion.o:   sfc/expansion/expansion.cpp
obj/sfc-coprocessor.o: sfc/coprocessor/coprocessor.cpp
obj/sfc-slot.o:        sfc/slot/slot.cpp
