# source list copy+pasted from fs-uae/Makefile.am
#	src/ar.cpp
#	src/archivers/zip/unzip.cpp
#	src/archivers/zip/unzip.h
#	src/blkdev_cdimage.cpp
#	src/cfgfile.cpp

libuae_a_SOURCES = \
	src/a2065.cpp \
	src/a2091.cpp \
	src/akiko.cpp \
	src/amax.cpp \
	src/arcadia.cpp \
	src/archivers/chd/astring.h \
	src/archivers/chd/bitstream.h \
	src/archivers/chd/chd.h \
	src/archivers/chd/chdcd.h \
	src/archivers/chd/chdcdrom.h \
	src/archivers/chd/chdcodec.h \
	src/archivers/chd/chdtypes.h \
	src/archivers/chd/corefile.h \
	src/archivers/chd/coretmpl.h \
	src/archivers/chd/flac.h \
	src/archivers/chd/hashing.h \
	src/archivers/chd/huffman.h \
	src/archivers/chd/md5.h \
	src/archivers/chd/osdcore.h \
	src/archivers/chd/sha1.h \
	src/archivers/dms/cdata.h \
	src/archivers/dms/crc_csum.cpp \
	src/archivers/dms/crc_csum.h \
	src/archivers/dms/getbits.cpp \
	src/archivers/dms/getbits.h \
	src/archivers/dms/maketbl.cpp \
	src/archivers/dms/maketbl.h \
	src/archivers/dms/pfile.cpp \
	src/archivers/dms/pfile.h \
	src/archivers/dms/tables.cpp \
	src/archivers/dms/tables.h \
	src/archivers/dms/u_deep.cpp \
	src/archivers/dms/u_deep.h \
	src/archivers/dms/u_heavy.cpp \
	src/archivers/dms/u_heavy.h \
	src/archivers/dms/u_init.cpp \
	src/archivers/dms/u_init.h \
	src/archivers/dms/u_medium.cpp \
	src/archivers/dms/u_medium.h \
	src/archivers/dms/u_quick.cpp \
	src/archivers/dms/u_quick.h \
	src/archivers/dms/u_rle.cpp \
	src/archivers/dms/u_rle.h \
	src/archivers/mp2/kjmp2.cpp \
	src/archivers/mp2/kjmp2.h \
	src/archivers/wrp/warp.h \
	src/audio.cpp \
	src/autoconf.cpp \
	src/blitter.cpp \
	src/blkdev.cpp \
	src/bsdsocket.cpp \
	src/calc.cpp \
	src/casablanca.cpp \
	src/cd32_fmv.cpp \
	src/cd32_fmv_genlock.cpp \
	src/cdrom.cpp \
	src/cdtv.cpp \
	src/cdtvcr.cpp \
	src/cia.cpp \
	src/consolehook.cpp \
	src/cpuboard.cpp \
	src/cpummu.cpp \
	src/cpummu30.cpp \
	src/crc32.cpp \
	src/custom.cpp \
	src/debug.cpp \
	src/debuginfo.cpp \
	src/debugmem.cpp \
	src/def_icons.cpp \
	src/devices.cpp \
	src/disk.cpp \
	src/diskutil.cpp \
	src/dlopen.cpp \
	src/dongle.cpp \
	src/drawing.cpp \
	src/driveclick.cpp \
	src/enforcer.cpp \
	src/ethernet.cpp \
	src/events.cpp \
	src/expansion.cpp \
	src/fake86_cpu.cpp \
	src/fdi2raw.cpp \
	src/filesys.cpp \
	src/flashrom.cpp \
	src/fpp.cpp \
	src/fpp_native.cpp \
	src/fpp_softfloat.cpp \
	src/framebufferboards.cpp \
	src/fsdb.cpp \
	src/fsusage.cpp \
	src/gayle.cpp \
	src/gfxboard.cpp \
	src/gfxutil.cpp \
	src/hardfile.cpp \
	src/hrtmon.rom.cpp \
	src/ide.cpp \
	src/idecontrollers.cpp \
	src/identify.cpp \
	src/include/a2065.h \
	src/include/a2091.h \
	src/include/akiko.h \
	src/include/amax.h \
	src/include/ar.h \
	src/include/arcadia.h \
	src/include/audio.h \
	src/include/autoconf.h \
	src/include/blitter.h \
	src/include/blkdev.h \
	src/include/bsdsocket.h \
	src/include/calc.h \
	src/include/casablanca.h \
	src/include/catweasel.h \
	src/include/cd32_fmv.h \
	src/include/cdtv.h \
	src/include/cdtvcr.h \
	src/include/cia.h \
	src/include/clipboard.h \
	src/include/commpipe.h \
	src/include/consolehook.h \
	src/include/cpu_prefetch.h \
	src/include/cpuboard.h \
	src/include/cpummu.h \
	src/include/cpummu030.h \
	src/include/crc32.h \
	src/include/custom.h \
	src/include/debug.h \
	src/include/debugmem.h \
	src/include/devices.h \
	src/include/disk.h \
	src/include/diskutil.h \
	src/include/dongle.h \
	src/include/drawing.h \
	src/include/driveclick.h \
	src/include/enforcer.h \
	src/include/epsonprinter.h \
	src/include/ersatz.h \
	src/include/ethernet.h \
	src/include/events.h \
	src/include/execio.h \
	src/include/execlib.h \
	src/include/fake86_cpu.h \
	src/include/fdi2raw.h \
	src/include/filesys.h \
	src/include/flashrom.h \
	src/include/fpp.h \
	src/include/fpp-ieee-be.h \
	src/include/fpp-unknown.h \
	src/include/fsdb.h \
	src/include/fsusage.h \
	src/include/framebufferboards.h \
	src/include/gayle.h \
	src/include/genblitter.h \
	src/include/gensound.h \
	src/include/gfxboard.h \
	src/include/gfxfilter.h \
	src/include/gui.h \
	src/include/ide.h \
	src/include/idecontrollers.h \
	src/include/identify.h \
	src/include/ini.h \
	src/include/inputdevice.h \
	src/include/inputrecord.h \
	src/include/isofs.h \
	src/include/isofs_api.h \
	src/include/keyboard.h \
	src/include/keybuf.h \
	src/include/luascript.h \
	src/include/mackbd.h \
	src/include/mmu_common.h \
	src/include/moduleripper.h \
	src/include/native2amiga.h \
	src/include/native2amiga_api.h \
	src/include/ncr9x_scsi.h \
	src/include/ncr_scsi.h \
	src/include/newcpu.h \
	src/include/options.h \
	src/include/osemu.h \
	src/include/packed.h \
	src/include/parallel.h \
	src/include/pci.h \
	src/include/pci_hw.h \
	src/include/picasso96.h \
	src/include/readcpu.h \
	src/include/rommgr.h \
	src/include/rtc.h \
	src/include/rtgmodes.h \
	src/include/sampler.h \
	src/include/sana2.h \
	src/include/savestate.h \
	src/include/scp.h \
	src/include/scsi.h \
	src/include/scsidev.h \
	src/include/serial.h \
	src/include/sndboard.h \
	src/include/specialmonitors.h \
	src/include/statusline.h \
	src/include/sysdeps.h \
	src/include/tabletlibrary.h \
	src/include/traps.h \
	src/include/uae.h \
	src/include/uae/ahi.h \
	src/include/uae/api.h \
	src/include/uae/asm.h \
	src/include/uae/assert.h \
	src/include/uae/atomic.h \
	src/include/uae/attributes.h \
	src/include/uae/byteswap.h \
	src/include/uae/caps.h \
	src/include/uae/cdrom.h \
	src/include/uae/cycleunit.h \
	src/include/uae/debuginfo.h \
	src/include/uae/dlopen.h \
	src/include/uae/endian.h \
	src/include/uae/enum.h \
	src/include/uae/fs.h \
	src/include/uae/funcattr.h \
	src/include/uae/glib.h \
	src/include/uae/inline.h \
	src/include/uae/io.h \
	src/include/uae/jitconfig.h \
	src/include/uae/likely.h \
	src/include/uae/limits.h \
	src/include/uae/log.h \
	src/include/uae/maccess.h \
	src/include/uae/memory.h \
	src/include/uae/mman.h \
	src/include/uae/parser.h \
	src/include/uae/patch.h \
	src/include/uae/ppc.h \
	src/include/uae/qemu.h \
	src/include/uae/segtracker.h \
	src/include/uae/seh.h \
	src/include/uae/slirp.h \
	src/include/uae/socket.h \
	src/include/uae/string.h \
	src/include/uae/time.h \
	src/include/uae/types.h \
	src/include/uae/vm.h \
	src/include/uaeexe.h \
	src/include/uaeipc.h \
	src/include/uaenative.h \
	src/include/uaeresource.h \
	src/include/uaeserial.h \
	src/include/uni_common.h \
	src/include/unpacked.h \
	src/include/videograb.h \
	src/include/x86.h \
	src/include/xwin.h \
	src/include/zarchive.h \
	src/include/zfile.h \
	src/ini.cpp \
	src/inputdevice.cpp \
	src/isofs.cpp \
	src/jit/codegen_udis86.h \
	src/jit/codegen_x86.h \
	src/jit/compemu.h \
	src/jit/compemu_fpp.cpp \
	src/jit/compemu_midfunc_arm.h \
	src/jit/compemu_midfunc_x86.h \
	src/jit/compemu_support.cpp \
	src/jit/flags_x86.h \
	src/keybuf.cpp \
	src/logging.cpp \
	src/main.cpp \
	src/mame/a2410.cpp \
	src/mame/mameglue.h \
	src/mame/tm34010/tms34010.cpp \
	src/mame/tm34010/tms34010.h \
	src/memory.cpp \
	src/native2amiga.cpp \
	src/ncr9x_scsi.cpp \
	src/ncr_scsi.cpp \
	src/newcpu.cpp \
	src/newcpu_common.cpp \
	src/od-fs/ahi_winuae.cpp \
	src/od-fs/ahidsound.h \
	src/od-fs/ahidsound_new.cpp \
	src/od-fs/ahidsound_new.h \
	src/od-fs/blkdev-linux.cpp \
	src/od-fs/bsdsocket_posix.cpp \
	src/od-fs/callbacks.h \
	src/od-fs/cda_play.cpp \
	src/od-fs/cda_play.h \
	src/od-fs/cdimage_stubs.cpp \
	src/od-fs/charset.cpp \
	src/od-fs/clock.cpp \
	src/od-fs/defines.h \
	src/od-fs/driveclick.cpp \
	src/od-fs/filesys_host.cpp \
	src/od-fs/fsdb_host.cpp \
	src/od-fs/fsdb_host.h \
	src/od-fs/fsvideo.cpp \
	src/od-fs/gui.cpp \
	src/od-fs/hardfile_host.cpp \
	src/od-fs/include/direct3d.h \
	src/od-fs/include/registry.h \
	src/od-fs/include/resource.h \
	src/od-fs/include/uae/uae.h \
	src/od-fs/include/uae/uae_inputevents_def.h \
	src/od-fs/include/win32gui.h \
	src/od-fs/input.cpp \
	src/od-fs/inputrecord.cpp \
	src/od-fs/ioport.cpp \
	src/od-fs/ioport.h \
	src/od-fs/joystick.cpp \
	src/od-fs/keyboard.cpp \
	src/od-fs/libamiga.cpp \
	src/od-fs/machdep/arm/maccess.h \
	src/od-fs/machdep/generic/maccess.h \
	src/od-fs/machdep/m68k.h \
	src/od-fs/machdep/maccess.h \
	src/od-fs/machdep/machdep.h \
	src/od-fs/machdep/ppc/maccess.h \
	src/od-fs/machdep/rpt.h \
	src/od-fs/machdep/x86/maccess.h \
	src/od-fs/midi.cpp \
	src/od-fs/midi.h \
	src/od-fs/mman.cpp \
	src/od-fs/mouse.cpp \
	src/od-fs/mp3decoder.h \
	src/od-fs/parser.cpp \
	src/od-fs/paths.cpp \
	src/od-fs/roms.cpp \
	src/od-fs/sleep.h \
	src/od-fs/sound_fs.cpp \
	src/od-fs/spin.cpp \
	src/od-fs/sounddep/sound.h \
	src/od-fs/statusline.cpp \
	src/od-fs/stubs.cpp \
	src/od-fs/support.cpp \
	src/od-fs/sysconfig.h \
	src/od-fs/target.h \
	src/od-fs/threaddep/sem.h \
	src/od-fs/threaddep/thread.h \
	src/od-fs/threading.cpp \
	src/od-fs/uae_host.cpp \
	src/od-fs/uaemisc.cpp \
	src/od-fs/videograb_fs.cpp \
	src/od-fs/vpar.cpp \
	src/od-fs/vpar.h \
	src/od-fs/winuae_compat.h \
	src/od-fs/writelog_fs.cpp \
	src/od-win32/bsdsock.cpp \
	src/od-win32/caps/CapsAPI.h \
	src/od-win32/caps/Comtype.h \
	src/od-win32/caps/caps_win32.cpp \
	src/od-win32/caps/caps_win32.h \
	src/od-win32/clipboard_win32.cpp \
	src/od-win32/clipboard_win32.h \
	src/od-win32/debug_win32.h \
	src/od-win32/dxwrap.h \
	src/od-win32/md-fpp.h \
	src/od-win32/midi.h \
	src/od-win32/parser.h \
	src/od-win32/picasso96_win.cpp \
	src/od-win32/picasso96_win.h \
	src/od-win32/serial_win32.cpp \
	src/od-win32/win32.h \
	src/od-win32/win32gfx.h \
	src/od-win32/win32_uaenet.cpp \
	src/patch.cpp \
	src/pcem/codegen.h \
	src/pcem/codegen_x86-64.h \
	src/pcem/cpu.h \
	src/pcem/dma.h \
	src/pcem/ibm.h \
	src/pcem/keyboard.h \
	src/pcem/keyboard_at.h \
	src/pcem/mem.h \
	src/pcem/model.h \
	src/pcem/mouse.h \
	src/pcem/mouse_serial.h \
	src/pcem/nvr.h \
	src/pcem/pcemglue.h \
	src/pcem/pic.h \
	src/pcem/pit.h \
	src/pcem/sound.h \
	src/pcem/sound_cms.h \
	src/pcem/sound_speaker.h \
	src/pcem/timer.h \
	src/pcem/x86.h \
	src/pcem/x86_ops.h \
	src/pci.cpp \
	src/ppc/pixman-stubs.cpp \
	src/ppc/ppc.cpp \
	src/qemu.cpp \
	src/qemuvga/cirrus_vga.cpp \
	src/qemuvga/cirrus_vga_rop.h \
	src/qemuvga/cirrus_vga_rop2.h \
	src/qemuvga/cirrus_vga_template.h \
	src/qemuvga/es1370.cpp \
	src/qemuvga/esp.cpp \
	src/qemuvga/lsi53c710.cpp \
	src/qemuvga/lsi53c895a.cpp \
	src/qemuvga/ne2000.cpp \
	src/qemuvga/ne2000.h \
	src/qemuvga/pixel_ops.h \
	src/qemuvga/qemuaudio.h \
	src/qemuvga/qemumemory.h \
	src/qemuvga/qemuuaeglue.cpp \
	src/qemuvga/qemuuaeglue.h \
	src/qemuvga/queue.h \
	src/qemuvga/scsi/esp.h \
	src/qemuvga/scsi/scsi.h \
	src/qemuvga/vga.cpp \
	src/qemuvga/vga.h \
	src/qemuvga/vga_int.h \
	src/qemuvga/vga_template.h \
	src/random.cpp \
	src/readcpu.cpp \
	src/rommgr.cpp \
	src/rtc.cpp \
	src/sana2.cpp \
	src/savestate.cpp \
	src/scp.cpp \
	src/scsi.cpp \
	src/scsiemul.cpp \
	src/scsitape.cpp \
	src/segtracker.cpp \
	src/slirp_uae.cpp \
	src/softfloat/softfloat.cpp \
	src/softfloat/softfloat_decimal.cpp \
	src/softfloat/softfloat_fpsp.cpp \
	src/softfloat/softfloat_fpsp_tables.h \
	src/softfloat/softfloat.h \
	src/softfloat/softfloat-macros.h \
	src/softfloat/softfloat-specialize.h \
	src/softfloat/softfloat.cpp \
	src/softfloat/softfloat_decimal.cpp \
	src/softfloat/softfloat_fpsp.cpp \
	src/specialmonitors.cpp \
	src/statusline.cpp \
	src/support/socket.cpp \
	src/support/time.cpp \
	src/test_card.cpp \
	src/traps.cpp \
	src/uaeexe.cpp \
	src/uaelib.cpp \
	src/uaenative.cpp \
	src/uaeresource.cpp \
	src/uaeserial.cpp \
	src/vm.cpp \
	src/x86.cpp \
	src/zfile.cpp \
	src/zfile_archive.cpp
nodist_libuae_a_SOURCES = \
	gen/blit.h \
	gen/blitfunc.cpp \
	gen/blitfunc.h \
	gen/blittable.cpp \
	gen/compemu.cpp \
	gen/compstbl.cpp \
	gen/comptbl.h \
	gen/cpudefs.cpp \
	gen/cpustbl.cpp \
	gen/cputbl.h




UAE = $(ROOT_DIR)/fs-uae



SRCS = $(addprefix $(UAE)/, $(filter-out %.h, $(libuae_a_SOURCES) $(nodist_libuae_a_SOURCES)))

TARGET := uae.wbx

CCFLAGS = -Waddress -Wmissing-format-attribute -Wpointer-arith -Werror=missing-declarations \
	-DUAE -DFSUAE -DHAVE_CONFIG_H \
	-I$(ROOT_DIR) -I$(UAE)/src/include -I$(UAE)/src/od-fs/machdep \
	-I$(UAE)/src/softfloat -Igen \
	-std=gnu++17

include ../common.mak

# code generators that we build and run on the host machine

genout/build68k: \
	$(UAE)/src/build68k.cpp \
	$(UAE)/src/writelog.cpp

genout/genblitter: \
	$(UAE)/src/blitops.cpp \
	$(UAE)/src/genblitter.cpp \
	$(UAE)/src/writelog.cpp

genout/gencomp: \
	$(UAE)/src/jit/gencomp.cpp \
	$(UAE)/src/missing.cpp \
	$(UAE)/src/readcpu.cpp \
	gen/cpudefs.cpp

genout/gencpu: \
	$(UAE)/src/gencpu.cpp \
	$(UAE)/src/missing.cpp \
	$(UAE)/src/readcpu.cpp \
	gen/cpudefs.cpp

genout/genlinetoscr: \
	$(UAE)/src/genlinetoscr.cpp

genout/%:
	@mkdir -p $(@D)
	g++ -DFSUAE -Dstrnicmp=strncasecmp -I$(ROOT_DIR) -I$(UAE)/src/include -Wall -o $@ $^

.PHONY: generate-all clean-generate
generate-all: $(nodist_libuae_a_SOURCES)
clean-generate:
	rm -rf gen genout

gen/blit.h: genout/genblitter
	@mkdir -p $(@D)
	$< i > $@

gen/blitfunc.cpp: genout/genblitter gen/blitfunc.h
	$< f > $@

gen/blitfunc.h: genout/genblitter
	$< h > $@

gen/blittable.cpp: genout/genblitter gen/blitfunc.h
	$< t > $@

gen/compemu.cpp: genout/gencomp
	$<

gen/compstbl.cpp: gen/compemu.cpp

gen/comptbl.h: gen/compemu.cpp

gen/cpudefs.cpp: genout/build68k $(UAE)/src/table68k
	$< < $(UAE)/src/table68k > $@

gen/cpuemu_0.cpp: genout/gencpu
	cd gen && ../$< --optimized-flags

gen/cpuemu_11.cpp: gen/cpuemu_0.cpp

gen/cpuemu_13.cpp: gen/cpuemu_0.cpp

gen/cpuemu_20.cpp: gen/cpuemu_0.cpp

gen/cpuemu_21.cpp: gen/cpuemu_0.cpp

gen/cpuemu_22.cpp: gen/cpuemu_0.cpp

gen/cpuemu_23.cpp: gen/cpuemu_0.cpp

gen/cpuemu_24.cpp: gen/cpuemu_0.cpp

gen/cpuemu_31.cpp: gen/cpuemu_0.cpp

gen/cpuemu_32.cpp: gen/cpuemu_0.cpp

gen/cpuemu_33.cpp: gen/cpuemu_0.cpp

gen/cpuemu_34.cpp: gen/cpuemu_0.cpp

gen/cpuemu_35.cpp: gen/cpuemu_0.cpp

gen/cpuemu_40.cpp: gen/cpuemu_0.cpp

gen/cpuemu_50.cpp: gen/cpuemu_0.cpp

gen/cpustbl.cpp: gen/cpuemu_0.cpp

gen/cputbl.h: gen/cpuemu_0.cpp

gen/linetoscr.cpp: genout/genlinetoscr
	$< > $@
