/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.4-0-g2359383fc (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.4-0-g2359383fc"
#endif
#define SDL_REVISION_NUMBER 0
