rmdir /s /q build
mkdir build
SET GLSLANG_VALIDATOR_DIR="%cd%\glslangValidator"
cd build
cmake ..\citra -DENABLE_SDL2=OFF -DUSE_SYSTEM_SDL2=OFF -DENABLE_QT=OFF -DENABLE_QT_TRANSLATION=OFF -DENABLE_QT_UPDATER=OFF ^
 -DENABLE_TESTS=OFF -DENABLE_DEDICATED_ROOM=OFF -DENABLE_WEB_SERVICE=OFF -DENABLE_CUBEB=OFF -DENABLE_OPENAL=OFF ^
 -DENABLE_LIBUSB=OFF -DUSE_DISCORD_PRESENCE=OFF -DUSE_SYSTEM_BOOST=OFF -DUSE_SYSTEM_OPENSSL=OFF -DUSE_SYSTEM_LIBUSB=OFF ^
 -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=OFF -DENABLE_HEADLESS=ON -DCMAKE_PROGRAM_PATH=%GLSLANG_VALIDATOR_DIR% ^
 -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=ON -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl ^
 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -G Ninja
ninja
cd ..
