#!/bin/sh
MYPATH="`dirname \"$0\"`"
SYSROOT="`realpath \"$MYPATH/../../sysroot\"`"
export CC=$SYSROOT/bin/musl-clang
export CFLAGS="-O3 -mcmodel=large -mstack-protector-guard=global -fno-pic -fno-pie"
export LDFLAGS="-Wl,-no-pie"
./configure --static --prefix=$SYSROOT
