//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LuaCallback : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LuaCallback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LuaCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LuaCallback() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          LuaWrapPINVOKE.delete_LuaCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual int runCallback(System.IntPtr l) {
    int ret = (SwigDerivedClassHasMethod("runCallback", swigMethodTypes0) ? LuaWrapPINVOKE.LuaCallback_runCallbackSwigExplicitLuaCallback(swigCPtr, l) : LuaWrapPINVOKE.LuaCallback_runCallback(swigCPtr, l));
    return ret;
  }

  public LuaCallback() : this(LuaWrapPINVOKE.new_LuaCallback(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("runCallback", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateLuaCallback_0(SwigDirectorrunCallback);
    LuaWrapPINVOKE.LuaCallback_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(LuaCallback));
    return hasDerivedMethod;
  }

  private int SwigDirectorrunCallback(System.IntPtr l) {
    return runCallback(l);
  }

  public delegate int SwigDelegateLuaCallback_0(System.IntPtr l);

  private SwigDelegateLuaCallback_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(System.IntPtr) };
}
