;	Altirra - Atari 800/800XL emulator
;	Kernel ROM replacement - version inof
;	Copyright (C) 2008-2018 Avery Lee
;
;	Copying and distribution of this file, with or without modification,
;	are permitted in any medium without royalty provided the copyright
;	notice and this notice are preserved.  This file is offered as-is,
;	without any warranty.

.macro _KERNELSTR_VERSION
		dta		'3.17'
.endm

.macro _KERNELSTR_VERSION_INTERNAL
		dta		"3.17"
.endm
